// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46WNFzKXu9Tb-0NhGdKi51IjyYgjUZ7Y',
    appId: '1:25354303654:android:00f181edac182f55d2dc67',
    messagingSenderId: '25354303654',
    projectId: 'movielook-f6b47',
    storageBucket: 'movielook-f6b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpfn_8k-_ZX5aeFyb04B1KJefCyJ7Y2A',
    appId: '1:25354303654:ios:14814684ba52c479d2dc67',
    messagingSenderId: '25354303654',
    projectId: 'movielook-f6b47',
    storageBucket: 'movielook-f6b47.appspot.com',
    androidClientId: '25354303654-26j24535ujbn5ckgf5aktsksgjdkeiml.apps.googleusercontent.com',
    iosClientId: '25354303654-lru0glpa7tc02mgmsoq7rut205kk6qlu.apps.googleusercontent.com',
    iosBundleId: 'com.movielook.whatchlist',
  );
}
